---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uozue6fnilbt/public_html/
    - export SOURCEPATH=/home/uozue6fnilbt/repositories/AlexIII-Repo/web-alexIII/zValencia
    - /bin/cp -R $SOURCEPATH $DEPLOYPATH